- name: 'Build and deploy ✨✨RockStart✨✨'
  hosts: servers
  remote_user: '{{ user_name }}'
  vars:
    website: '✨✨RockStart✨✨'
    dns_name: 'adricristi.duckdns.org'
  roles:
    - cleanup
    - copy_resources
    - ssl_certificate
    - deploy
