- name: 'Build and deploy ✨✨RockStart✨✨'
  hosts: all
  vars:
    user_name: 'AdriCristi✨✨RockStart'
    website: '✨✨RockStart✨✨'
  remote_user: '{{ user_name }}'
  tasks:
    - name: 'Copy WordPress resources to the hosts'
      ansible.builtin.copy:
        src: './{{ website }}'
        dest: '/home/{{ user_name }}/'
        owner: '{{ user_name }}'
        group: '{{ user_name }}'
        mode: '0644'
    - name: 'Build the images for the WoldPress, PHPMyAdmin, and DB'
      community.docker.docker_compose:
        project_src: '/home/{{ user_name }}/{{ website }}'
        build: yes
      register: output
    - name: 'Run the script to install {{ website }}'
      community.docker.docker_container_exec:
        container: wp_wordpress
        command: /bin/bash /opt/install_rockstart.sh