---
- name: 'Updating apt and upgrading packages'
  apt:
    update_cache: yes
    upgrade: yes
- name: 'Installing {{ item }}'
  apt:
    name: '{{ item }}'
  loop:
    - docker
    - docker-compose
- name: Download docker-compose v2.3.4
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.3.4/docker-compose-linux-x86_64
    dest: /usr/bin/docker-compose
    mode: '0755'
